version: 2.1

commands:
  printpipelineid:
    parameters:
      id:
        type: string
    steps:
      - run: echo "I love coding"
      - run: echo <<parameters.id>>
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "building source code"
          command: npm i
      - save_cache:
          key: "dependencies"
          paths:
            - /src/node_modules
      - run: npm run build



workflows:
  say-hello-workflow:
    jobs:
      - build
          
